hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task:
    - strategy.optimalDTE=43,44,45,46,47,48
    - strategy.maxCapitalToUse=0.3,0.35,0.40,0.45
    - strategy.maxCapitalToUsePerTrade=0.2,0.3,0.4
    - strategy.closeDuration=21
    - strategy.optPutToSellDelta=range(-0.20,-0.12,0.025)
    - strategy.optPutToBuyDelta=range(-0.09,-0.01,0.02)
  job:
    name: backTester
    override_dirname: strategy.closeDuration=21,strategy.maxCapitalToUse=0.3,0.35,0.40,0.45,strategy.maxCapitalToUsePerTrade=0.2,0.3,0.4,strategy.optPutToBuyDelta=range(-0.09,-0.01,0.02),strategy.optPutToSellDelta=range(-0.20,-0.12,0.025),strategy.optimalDTE=43,44,45,46,47,48
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.1
    cwd: /Users/msantoro/PycharmProjects/Backtester
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/msantoro/PycharmProjects/Backtester/sweepConfig
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      strategy: putVerticalOnDownMove
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: joblib
      hydra/output: default
  verbose: false
strategy:
  strategyName: PUT_VERTICAL_ON_DOWN_MOVE
  optPutToSellDelta: -0.2
  maxPutToSellDelta: -0.25
  minPutToSellDelta: -0.11
  optPutToBuyDelta: -0.05
  maxPutToBuyDelta: -0.1
  minPutToBuyDelta: -0.005
  underlyingTicker: SPX
  orderQuantity: 1
  expCycle: MONTHLY
  optimalDTE: 45
  minimumDTE: 40
  maxBidAsk: 15
  percentDownToTrigger: -0.01
  numberDaysForMovingAverage: 0
  riskManagement: CLOSE_AT_50_PERCENT
  closeDuration: 21
  startingCapital: 1000000
  maxCapitalToUse: 0.25
  maxCapitalToUsePerTrade: 0.25
  startDateTime: 01/03/2005
